### ISSUE TITLE
Use proton instead of wine

### ISSUE THREAD

**Issue by hades200082** [mbround18/enshrouded-docker#23]
I've seen and experienced a ton of lag and performance issues with this docker image. 

From conversations on Reddit it seems that others have identified wine as the cause of this lag and the other docker image that uses proton doesn't have any lag issues.

**Comment by mbround18** [comment]
Hmm I haven't played much with proton but I could give it a whirl. Since its just me developing this might take me a bit as I want to wrap up the v2 of this container to get it onto the rust cli.

**Comment by hades200082** [comment]
@mbround18 FYI I've just done a test on our save game using your wine-based preview version and the proton-based one from https://github.com/mornedhels/enshrouded-server

When running yours I get the red server is overloaded message almost constantly with only 2 players in the game, but it's mostly playable with a little rubber-banding.

If I have 3 players in the game then the rubber-banding gets worse and we get a fair bit of the game suddenly teleporting us to a different location (presumably where the server thinks we should be).

4 players is basically unplayable.

---

Running the proton-based image I get none of those issues. The red overloaded message shows up occasionally at 4 players when we're all very separated or when we go into an area with a lot of activity.

**Comment by mbround18** [comment]
I can take a look at that dockerfile

**Comment by kg5hfl** [comment]
> Alright apologies this took a while, I had to basically revamp my [whole pipeline system](https://github.com/mbround18/gh-reusable), i have https://github.com/mbround18/steamcmd-bases which i im working on the proton container, wine, and base
> 
> Working on testing it for a variety of game servers

Is there a way to run it with proton using docker compose? I ask, because I'm a noob and just got the docker compose figured out. 

thanks in advance.

**Comment by mbround18** [comment]
Hey @kg5hfl im still working on the proton adaptation of this

**Comment by mbround18** [comment]
Alright, as an update im still chugging away at this, I have a container with proton using [umu-launcher](https://github.com/Open-Wine-Components/umu-launcher) but im still hitting an issue where its not actually launching the application it just exists with code 0. 

Still trying to figure out all the requirements

**Comment by mbround18** [comment]
UMU added to proton base
https://github.com/mbround18/steamcmd-bases/pull/8

UMU launch configurations
https://github.com/mbround18/game-server-management/pull/79

**Comment by mbround18** [comment]
Almost there .. got it launching with proton right now, just gotta figure out the right configs


```sh
Final command: cd "/home/steam/enshrouded" && PROTON_DUMP_DEBUG_COMMANDS="0" PROTON_LOG="0" PROTON_NO_ESYNC="0" PROTON_NO_FSYNC="0" PROTON_USE_WINED3D="0" STEAM_COMPAT_CLIENT_INSTALL_PATH="/home/steam/.proton/prefixes/gsm" STEAM_COMPAT_DATA_PATH="/home/steam/.proton/prefixes/gsm" STEAM_RUNTIME="1" SteamAppId="0" SteamGameId="0" "/home/steam/.steam/steam/compatibilitytools.d/GE-Proton10-1/proton" "runinprefix" "enshrouded_server.exe"
enshrouded-1  | 📡 Monitoring Enshrouded server logs...
```


```sh
enshrouded-1  | 2025-05-18T23:43:03.041455Z  INFO instance: [app] start creation step Init
enshrouded-1  | 2025-05-18T23:43:03.041457Z  INFO instance: [app] start creation step Init_Steamworks
enshrouded-1  | 2025-05-18T23:43:03.148507Z  INFO instance: 0198:err:steamclient:steamclient_init unable to load native steamclient library
enshrouded-1  | 2025-05-18T23:43:03.148524Z  INFO instance: 0198:err:msvcrt:_wassert (L"!status",L"../src-lsteamclient/steamclient_main.c",375)
enshrouded-1  | 2025-05-18T23:43:03.148527Z  INFO instance: Assertion failed: !status, file ../src-lsteamclient/steamclient_main.c, line 375
enshrouded-1  | 2025-05-18T23:43:03.148529Z  INFO instance:
```

**Comment by Hr46ph** [comment]
Don't mind me asking, any more progress you can share on this?

Thanks!

**Comment by hades200082** [comment]
To be fair, the other proton-based docker image has issues currently - https://github.com/mornedhels/enshrouded-server/issues/143

**Comment by mbround18** [comment]
@Hr46ph i am still working on this, had to take a little break with family visiting but back on it. I have a base image working [mbround18/steamcmd-bases](https://github.com/mbround18/steamcmd-bases) but im wokring on figuring out why enshrouded isnt launching

**Comment by JustM1k** [comment]
> To be fair, the other proton-based docker image has issues currently - [mornedhels/enshrouded-server#143](https://github.com/mornedhels/enshrouded-server/issues/143)

I tried GE-Proton10-10 - it works fine.

**Comment by mbround18** [comment]
hmm what env vars did you use?

**Comment by JustM1k** [comment]
> hmm what env vars did you use?

docker-compose.yml
```
services:
  enshrouded:
    build:
      context: .
      dockerfile: dockerfiles/proton.Dockerfile
      args:
        - GE_PROTON_VERSION=10-10
    image: mornedhels/enshrouded-server:dev-proton
    container_name: enshrouded
    hostname: enshrouded
    restart: unless-stopped
    stop_grace_period: 90s
    ports:
      - "15637:15637/udp"
    volumes:
      - ./game:/opt/enshrouded
    environment:
      - SERVER_NAME=AlcoWorld
      - SERVER_ROLE_0_PASSWORD=****
      - SERVER_ROLE_0_CAN_KICK_BAN=true
      - SERVER_ROLE_0_CAN_ACCESS_INVENTORIES=true
      - SERVER_ROLE_0_CAN_EDIT_BASE=true
      - SERVER_ROLE_0_CAN_EXTEND_BASE=true
      - SERVER_ROLE_0_RESERVED_SLOTS=1
      - SERVER_ROLE_1_NAME=Friends
      - SERVER_ROLE_1_PASSWORD=****
      - SERVER_ROLE_1_CAN_KICK_BAN=false
      - SERVER_ROLE_1_CAN_ACCESS_INVENTORIES=true
      - SERVER_ROLE_1_CAN_EDIT_BASE=true
      - SERVER_ROLE_1_CAN_EXTEND_BASE=true
      - SERVER_ROLE_1_RESERVED_SLOTS=2
      - PUID=4711
      - PGID=4711
      - UPDATE_CRON=*/30 * *
      - log_level=50

volumes:
  game:
```

Dockerfile
```
FROM steamcmd/steamcmd:ubuntu-24@sha256:33d7abffc910756198d3e6972759ecbebe7119288bb904ee796a8df1756c902a AS builder

ARG GE_PROTON_VERSION="10-10"

# Install prerequisites
RUN dpkg --add-architecture i386 \
    && apt-get update \
    && DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends \
        curl \
        tar \
        dbus \
    && apt autoremove --purge && apt clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# install proton
RUN curl -sLOJ "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton${GE_PROTON_VERSION}/GE-Proton${GE_PROTON_VERSION}.tar.gz" \
    && mkdir -p /tmp/proton \
    && tar -xzf GE-Proton*.tar.gz -C /tmp/proton --strip-components=1 \
    && rm GE-Proton*.* \
    && rm -f /etc/machine-id \
    && dbus-uuidgen --ensure=/etc/machine-id


FROM steamcmd/steamcmd:ubuntu-24@sha256:33d7abffc910756198d3e6972759ecbebe7119288bb904ee796a8df1756c902a
LABEL maintainer="docker@mornedhels.de"

# Install dependencies
RUN dpkg --add-architecture i386 \
    && apt-get update \
    && DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends \
        curl \
        supervisor \
        cron \
        rsyslog \
        jq \
        zip \
        python3 \
        python3-pip \
        libfreetype6 \
        libfreetype6:i386 \
    && apt autoremove --purge && apt clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install winetricks (unused)
RUN curl -o /tmp/winetricks https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks \
    && chmod +x /tmp/winetricks && install -m 755 /tmp/winetricks /usr/local/bin/winetricks \
    && rm -rf /tmp/*

# MISC
RUN mkdir -p /usr/local/etc /var/log/supervisor /var/run/enshrouded /usr/local/etc/supervisor/conf.d/ /opt/enshrouded /home/enshrouded/.steam/sdk32 /home/enshrouded/.steam/sdk64 \
    && groupadd -g "${PGID:-4711}" -o enshrouded \
    && useradd -g "${PGID:-4711}" -u "${PUID:-4711}" -o --create-home enshrouded \
    && ln -f /root/.steam/sdk32/steamclient.so /home/enshrouded/.steam/sdk32/steamclient.so \
    && ln -f /root/.steam/sdk64/steamclient.so /home/enshrouded/.steam/sdk64/steamclient.so \
    && sed -i '/imklog/s/^/#/' /etc/rsyslog.conf \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY --from=builder /tmp/proton /usr/local/bin
COPY --from=builder /etc/machine-id /etc/machine-id

COPY ../supervisord.conf /etc/supervisor/supervisord.conf
COPY --chmod=755 ../scripts/default/* ../scripts/proton/* /usr/local/etc/enshrouded/

WORKDIR /usr/local/etc/enshrouded
CMD ["/usr/local/etc/enshrouded/bootstrap"]
ENTRYPOINT []
```
