### ISSUE TITLE
Not Starting Docker Desktop Windows

### ISSUE THREAD

**Issue by domesticwarlord86** [mbround18/enshrouded-docker#5]
Hey there, I'm trying to run this docker container using Docker desktop for Windows. I created a `docker-compose.yml` files exactly like the one in your example, loaded powershell and ran docker compose up -d. It starts, but every time it closes. The last line of the log file is `0024:err:virtual:virtual_setup_exception stack overflow 1808 bytes addr 0x170024de1 stack 0x208f0 (0x20000-0x21000-0x120000)`. I posted the whole log here on Pastebin for you but I'm eally not sure where to go from here. Any advice would be appreciated. Thank you.

https://pastebin.com/uXLEBKzN

**Comment by mbround18** [comment]
What cpu are you running?

**Comment by domesticwarlord86** [comment]
> What cpu are you running?

```Device name	AllMight
Processor	Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz   2.90 GHz
Installed RAM	64.0 GB
System type	64-bit operating system, x64-based processor
Edition	Windows 10 Pro
Version	22H2
Installed on	‎2/‎14/‎2024
OS build	19045.4046
Experience	Windows Feature Experience Pack 1000.19053.1000.0
```

**Comment by domesticwarlord86** [comment]
> Could you try without the platofrm specification on the docker-compose?

So I attempted with this compose file: 

```
services:
  enshrouded:
    container_name: enshrouded
    image: mbround18/enshrouded-docker:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_NAME: "DW's Enshrouded Server" # Optional, Name of the server
      PASSWORD: "pass" # Optional, Password for the server
    #      SAVE_DIRECTORY: ./savegame # Optional, Save directory for the game
    #      LOG_DIRECTORY: ./logs # Optional, Log directory for the server
      SERVER_IP: X.X.X.X # Optional, IP address for the server
      GAME_PORT: 15636 # Optional, Game port for the server
      QUERY_PORT: 15637 # Optional, Query port for the server
    #      SLOT_COUNT: 16 # Optional, Number of slots for the server
    ports:
      - "15636:15636/udp"
      - "15636:15636/tcp"
      - "15637:15637/udp"
      - "15637:15637/tcp"
    volumes:
      - .data:/home/steam/enshrouded

networks:
  default:
    name: cloudflared
    external: true
```
    
It did not work. Producing the same errors:
```
2024-02-17 10:25:00 enshrouded  | 0050:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
2024-02-17 10:25:00 enshrouded  | 0050:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
2024-02-17 10:25:00 enshrouded  | 0050:err:systray:initialize_systray Could not create tray window
2024-02-17 10:25:01 enshrouded  | 0024:err:virtual:virtual_setup_exception stack overflow 1808 bytes addr 0x170024de1 stack 0x208f0 (0x20000-0x21000-0x120000)
enshrouded exited with code 1
```

However I think I found the issue. 

When setting up a few other containers, particularly overseerr I was running into an issue and found this on their documentation https://docs.overseerr.dev/getting-started/installation#windows. Particularly the part about volumes on windows. So I decided to try that logic and apply it to this container.

```
services:
  enshrouded:
    container_name: enshrouded
    image: mbround18/enshrouded-docker:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_NAME: "DW's Enshrouded Server" # Optional, Name of the server
      PASSWORD: "pass" # Optional, Password for the server
    #      SAVE_DIRECTORY: ./savegame # Optional, Save directory for the game
    #      LOG_DIRECTORY: ./logs # Optional, Log directory for the server
      SERVER_IP: X.X.X.X # Optional, IP address for the server
      GAME_PORT: 15636 # Optional, Game port for the server
      QUERY_PORT: 15637 # Optional, Query port for the server
    #      SLOT_COUNT: 16 # Optional, Number of slots for the server
    ports:
      - "15636:15636/udp"
      - "15636:15636/tcp"
      - "15637:15637/udp"
      - "15637:15637/tcp"
    volumes:
      - enshrouded-data:/home/steam/enshrouded

volumes:
  enshrouded-data:
```
    
This worked. Allowing the server to fully boot and for me to connect to it.
